# docker-compose build
# docker-compose up -d web
version: '3'
volumes:
  nginx-logs:
  nginx-html:
  nginx-conf:
  nginx-sites:
  nginx-ssl:

services:
  nginx:
    image: nginx:latest
    container-name: nginx-sekm
    volumes:
      #- nginx-conf:/etc/nginx/nginx.conf
      #- nginx-data:/usr/share/nginx/html
      - ./logs:/var/log/nginx
      - ./html:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf 
      - ./conf/sites:/etc/nginx/sites 
      - ./conf/ssl:/etc/nginx/ssl \

    environment:
      - NGINX_HOST=docker.sysnet.nagano
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - nginx_network
    healthcheck:
      test: "exit 0"

networks:
  nginx_network:
    external: true



# docker run --name nginx-sekm -p 80:80 -p 443:443 \
#    -v $HOME/nginx-sekm/logs:/var/log/nginx \
#    -v $HOME/nginx-sekm/html:/usr/share/nginx/html:ro \
#    -v $HOME/nginx-sekm/conf/nginx.conf:/etc/nginx/nginx.conf \
#    -v $HOME/nginx-sekm/conf/sites:/etc/nginx/sites \
#    -v $HOME/nginx-sekm/conf/ssl:/etc/nginx/ssl \
#    -d nginx